table_create = ''' create table if not exists public.airbnb_listings
(
    id                                           bigint,
    listing_url                                  text,
    scrape_id                                    bigint,
    last_scraped                                 date,
    source                                       text,
    name                                         text,
    description                                  text,
    neighborhood_overview                        text,
    picture_url                                  text,
    host_id                                      bigint,
    host_url                                     text,
    host_name                                    text,
    host_since                                   date,
    host_location                                text,
    host_about                                   text,
    host_response_time                           text,
    host_response_rate                           text,
    host_acceptance_rate                         text,
    host_is_superhost                            text,
    host_thumbnail_url                           text,
    host_picture_url                             text,
    host_neighbourhood                           text,
    host_listings_count                          integer,
    host_total_listings_count                    integer,
    host_verifications                           text,
    host_has_profile_pic                         text,
    host_identity_verified                       text,
    neighbourhood                                text,
    neighbourhood_cleansed                       text,
    neighbourhood_group_cleansed                 text,
    latitude                                     double precision,
    longitude                                    double precision,
    latitude_longitude                           point,
    property_type                                text,
    room_type                                    text,
    accommodates                                 integer,
    bathrooms                                    double precision,
    bathrooms_text                               text,
    bedrooms                                     integer,
    beds                                         integer,
    amenities                                    text,
    price                                        text,
    minimum_nights                               integer,
    maximum_nights                               integer,
    minimum_minimum_nights                       integer,
    maximum_minimum_nights                       integer,
    minimum_maximum_nights                       integer,
    maximum_maximum_nights                       integer,
    minimum_nights_avg_ntm                       double precision,
    maximum_nights_avg_ntm                       double precision,
    calendar_updated                             text,
    has_availability                             text,
    availability_30                              integer,
    availability_60                              integer,
    availability_90                              integer,
    availability_365                             integer,
    calendar_last_scraped                        date,
    number_of_reviews                            integer,
    number_of_reviews_ltm                        integer,
    number_of_reviews_l30d                       integer,
    first_review                                 text,
    last_review                                  text,
    review_scores_rating                         double precision,
    review_scores_accuracy                       double precision,
    review_scores_cleanliness                    double precision,
    review_scores_checkin                        double precision,
    review_scores_communication                  double precision,
    review_scores_location                       double precision,
    review_scores_value                          double precision,
    license                                      text,
    instant_bookable                             text,
    calculated_host_listings_count               integer,
    calculated_host_listings_count_entire_homes  integer,
    calculated_host_listings_count_private_rooms integer,
    calculated_host_listings_count_shared_rooms  integer,
    reviews_per_month                            double precision
); '''
